# Generated by Django 3.1.1 on 2020-09-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('under_construction_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotify',
            name='comment',
            field=models.TextField(default='Tuma maoni..'),
        ),
    ]
